### ISSUE TITLE
LOINC codes specified in the FHIR Profile do not appear in the Logical Model

### ISSUE THREAD

**Issue by mlterryMitre** [standardhealth/shr-cli#114]
Associated with HL7 Breast Cancer Model May 2018 Ballot Comment [#16163](https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=16163&start=0). 

Example:
In the FHIR profile for HER2byISH (http://hl7.org/fhir/us/breastcancer/StructureDefinition-oncology-HER2byISH.html), 
Observation/cimi-statement-DiagnosticService-extension/category/component[3]/coding/code shows a fixed value of **74861-6** for averageCEP17SignalsPerCell.

The equivalent logical model for HER2byISH (http://hl7.org/fhir/us/breastcancer/StructureDefinition-oncology-HER2byISH-model.html), the URL under type for 
oncology-HER2byISH-model/evaluationResultTopic/evaluationComponent/averageCEP17SignalsPerCell is missing the **_code_** element.
![image](https://user-images.githubusercontent.com/40579130/42709242-d58c57b4-86ad-11e8-9e4b-972902835853.png)

This also affects the other components under Observation/cimi-statement-DiagnosticService-extension/category in the same profile (averageHER2SignalsPerCell and hER2toCEP17Ratio).

**Comment by cmoesel** [comment]
This is actually working as expected. The reason that the LOINC code does not show up as an attribute in the logical model is because it is not a value or field in our CIMPL model either; it is the _Concept_ of the data element.

![image](https://user-images.githubusercontent.com/2278253/42891479-766e2950-8a7d-11e8-8cb3-bb01ab861a7f.png)

In the logical models, the data element _Concept_ doesn't get mapped to a model element, but instead gets mapped as one of the keywords for the model.  If you look at the JSON structure definition for the _oncology-AverageCEP17SignalsPerCell-model_ logical model, you'll see:

![image](https://user-images.githubusercontent.com/2278253/42891629-cb03173c-8a7d-11e8-9b1b-dd2b2d3e4f5b.png)

The reason it shows up in the FHIR _profiles_ as an element is because there is a specific mapping statement that maps the _Concept_ to _component.code_:

![image](https://user-images.githubusercontent.com/2278253/42891764-229e45fc-8a7e-11e8-8935-96c3a5c1ce67.png)

If we wanted the LOINC code to show up as an element in the model, we'd need to describe what that should look like -- but it may be most appropriate just to have it as a keyword since the model identifier itself provides the context for what it is.

**Comment by cmoesel** [comment]
I discussed this with @markkramerus.  It's important that reviewers at least _see_ the LOINC code when reviewing the model.  There are a few potential approaches:

1. Update the IG generator to put the LOINC code into the description of the logical model on its page (as a table or something else that will stand out enough to be noticed).
2. Update the CIMPL definitions of the evaluation components to include a code property that is fixed to the appropriate LOINC code.
3. Update the tooling to auto-create an element on logical models that will contain the fixed _Concept_ code.

@markkramerus will consider the options.

**Comment by markkramerus** [comment]
Moved to CIMPL-42 (https://standardhealthrecord.atlassian.net/browse/CIMPL-42)
