### ISSUE TITLE
A dedicated Range FHIR Profile was incorrectly created

### ISSUE THREAD

**Issue by mlterryMitre** [standardhealth/shr-cli#116]
Identified in the Breast Cancer Model FHIR IG May 2018 Ballot comment [#16176](https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=16176&start=0).  

SHR created a dedicated profile for reference ranges called RangeProfile (http://hl7.org/fhir/us/breastcancer/StructureDefinition-shr-core-Range.html).  This is unnecessary since the Breast Cancer IG defines Range in the same way that FHIR does.

**Comment by cmoesel** [comment]
This seems to be because our SimpleQuantity profile constrains `value` to `1..1`, when FHIR's SimpleQuantity's `value` is `0..1`.  That said, looking at the CIMPL, I don't see how/where the `value` is getting set to `1..1`.

Will need further investigation.

**Comment by cmoesel** [comment]
OK.  There are two things going on here.

1. In the `shimi` branch right now, `Quantity` has this `Value` declaration:
```
Value:			decimal
```
This will default the value's cardinality to `1..1`.  In FHIR Quantity (and all its profiles, like SimpleQuantity), the `value` is `0..1`.  This causes our tooling to spit out profiles for Quantity, SimpleQuantity, Age, etc., with a `1..1` constraint on `value`.  As a result, the Range then requires _our_ profile of SimpleQuantity, so Range must be a profile too (since it now has a _difference_ from the FHIR Range).

This first issue can be fixed by changing the Quantity value declaration in the CIMPL to:
```
Value:			0..1 decimal
```

2. Even with that, however, there was a bug in the FHIR export code that still produced a profile for Range, because it still was creating a differential element on the `low` and `high` elements even though they weren't needed.  This requires a code fix which I have locally and will push to a branch soon.

**Comment by markkramerus** [comment]
Closing. We have addressed the no-diff issue and also have the no profile flag.
