### ISSUE TITLE
Error: Could not determine how to map nested value (ERROR_CODE: 13060)

### ISSUE THREAD

**Issue by mlterryMitre** [standardhealth/shr-cli#120]
I receive the above error if directly referencing more than one Entry Element nested.  Flagged as a bug after review with @markkramerus and agreement that this type of nested reference should be supported.

The example CIMPL syntax used is below:
_EntryElement:	BreastClinicalLymphNodeInvolvement
Based on:		LaboratoryObservation
Concept:		MTH#C0806692 "Lymph Node Involvement" 
Description:	"Clinical assessment of lymph nodes for presence of cancer cells in staging the N category in cancers."
0..0			ObservationContext.ResultValue
0..0			ObservationContext.ExceptionValue
			LaboratoryObservationTopic.TopicCode is MTH#C0806692 "Lymph Node Involvement"  
0..0			LaboratoryObservationTopic.DiagnosticService  // This is a clinical evaluation, not part of DiagnosticServiceVS
0..0			LaboratoryObservationTopic.Precondition
			**LaboratoryObservationTopic.Specimen.CollectionSite value is type BreastLymphNodeBodySite
			LaboratoryObservationTopic.Specimen.CollectionMethod from LymphNodeClinicalMethodVS**_

The workaround for this is for me to create a new Element or EntryElement for Specimen:
_EntryElement:	BreastClinicalLymphNodeInvolvement
Based on:		LaboratoryObservation
Concept:		MTH#C0806692 "Lymph Node Involvement" 
Description:	"Clinical assessment of lymph nodes for presence of cancer cells in staging the N category in cancers."
0..0			ObservationContext.ResultValue
0..0			ObservationContext.ExceptionValue
				LaboratoryObservationTopic.TopicCode is MTH#C0806692 "Lymph Node Involvement" 
0..0			LaboratoryObservationTopic.DiagnosticService  // This is a clinical evaluation, not part of DiagnosticServiceVS
0..0			LaboratoryObservationTopic.Precondition
			**LaboratoryObservationTopic.Specimen is type BreastLymphNodeSpecimen**_

followed by...
_EntryElement:	BreastLymphNodeSpecimen
Based on:		Specimen
Description:	"A body site specific to the lymph node structure."
				Type from BreastSpecimenTypeVS 
				CollectionSite value is type BreastLymphNodeBodySite  // mlt: which is type AnatomicalLocation
			CollectionMethod from LymphNodeClinicalMethodVS
0..0			SourceSpecimen_

**Comment by cmoesel** [comment]
Actually, I _think_ the error `Error: Could not determine how to map nested value (ERROR_CODE: 13060)` is correct in this circumstance.  Here is why:

In your `BreastClinicalLymphNodeInvolvement`, you have:
```
LaboratoryObservationTopic.Specimen.CollectionSite value is type BreastLymphNodeBodySite
LaboratoryObservationTopic.Specimen.CollectionMethod from LymphNodeClinicalMethodVS
```

The active mapping that applies here inherited from the `Observation` mapping and is:
```
ObservationTopic.Specimen maps to specimen
```

Now... your definitions refer to `CollectionSite` and `CollectionMethod` within the SHR Specimen -- so we need to know how to map those into the referenced FHIR `Specimen`.  But if you look at the `Specimen` mapping, it does not map those elements to FHIR at all!  So it is true that the tooling can't figure out how to map the `CollectionSite` and `CollectionMethod` because no one has told it _how_.

I was able to fix the problem by adding these mappings to the `Specimen` mapping:
```
CollectionSite.AnatomicalLocation maps to collection.bodySite
CollectionMethod.CodeableConcept maps to collection.method
```

**Comment by cmoesel** [comment]
Now... that does lead to a different question -- why did your workaround work?  I haven't looked at it, but I'm guessing that the `BreastLymphNodeSpecimen` profile that was created ends up representing the `CollectionSite` and `CollectionMethod` as _extensions_ (since they're not mapped).

Which means that maybe your original code should have worked, and maybe the SHR tooling should have expanded out the SHR Specimen _profile_ and applied the value set and type bindings to the _extensions_.  Hmmm... I'll have to think on that, but it seems like actually mapping those to the right properties in FHIR `Specimen` is probably the right way to go anyway.

**Comment by mlterryMitre** [comment]
Thanks @cmoesel.  Yeh...I see now how separately creating a Specimen element created a FHIR extensions and the result just piled on duplicate elements.  

So, looking at this again, I suppose this  change is to cimi_entity_map.txt and then I should be able to create that original reference to `LaboratoryObservationTopic.Specimen.CollectionSite value is type BreastLymphNodeBodySite` 
in `EntryElement:	BreastClinicalLymphNodeInvolvement` ?

**Comment by mlterryMitre** [comment]
Tried this fix to cimi_entity_map.txt and verified the original change now exports without errors.  pushed to shimi under commit [36b5231](https://github.com/standardhealth/shr_spec/commit/50ef361c4d356b478637019f85d37d1cf74908bc).
