### ISSUE TITLE
Extension naming simplification?

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#127]
Our naming convention for extensions is namespace-element name-extension, for example, shr-base-TopicCode-extension.  This seems out of step with the way other extensions (defined by FHIR and other work groups) are named; they seem to just use a readable name. Could we simplify our naming to "TopicCode" for the purposes of the IG?  We don't have to change the unique URL.
Note that the full URL for the extension is included in the instance data, so in practice, this shouldn't cause a name collision.

**Comment by cmoesel** [comment]
I'll take a look at this to see what we can do.  It seems to be a reasonable request, but I need to see where the IG documentation generator is pulling the name from -- and if that is required to be unique.  One potential issue is that we have some things that have both a profile representation and an extension representation -- and their identifiers need to be unique.

**Comment by cmoesel** [comment]
Unfortunately, when an extension is used in a profile, the snapshot view in the IG displays the extension's `id` rather than name or title.  In the example above, the `id` is `shr-base-TopicCode-extension`.

The problem with simplifying the `id` is two-fold:

1. the `id` must be unique in the IG
2. the `id` must match the last part of the identifying `uri`

If we simplify something like `my-namespace-MyElement-extension` to just `MyElement`, there are two potential ways we could end up w/ duplicate `id`s:

1. If we need to represent `MyElement` as both a profile and an extension, then they'd both have the same simplified `id`.  You could disambiguate by adding `-extension`, which is what I did.
2. If there was a `MyElement` in two different namespaces, then they'd both have the same simplified `id`.  You could disambiguate by adding the namespace, which is what I did.

We could dynamically determine if either of these name clashes happen and only disambiguate if necessary, but then there is a possibility that if we add elements in a future version that cause an ambiguity, we'd change the already published `id` -- which is not a good thing.

**Comment by markkramerus** [comment]
Interesting discussion, perhaps relevant to modularization. Copied remarks into the wiki https://github.com/standardhealth/shr_spec/wiki/Modularity-and-Packaging
