### ISSUE TITLE
Need Profile and Extension FQNs That Don't Change from IG to IG

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#137]
(This is an issue that needs to become a Jira project...soon...)
No matter which implementation guide we generate from SHR sources, or what kind of filtering we do, or what we put in the config file, profiles and extensions must always have the same fully qualified names. 

- Right now, if I run the oncocore IG (aka MCODE), the Patient profile is named: http://hl7.org/fhir/us/oncocore/StructureDefinition/shr-entity-Patient.
- If I run the same source but generate the occupational health IG, the same profile is named: http://hl7.org/fhir/us/odh/StructureDefinition/shr-entity-Patient.

The name can't change. It's the same profile.

**Comment by cmoesel** [comment]
To support this feature, we need either the planned modular feature (CIMPL packages) **or** we need a way to associate namespaces/elements to URL prefixes.  Otherwise there is no way that the FHIR exporter can know that you already exported the same patient definition in a _different_ IG with a _different_ IG URL prefix.

**Comment by markkramerus** [comment]
I did some investigation, and it seems the pattern for FQN is [fhirURL]/StructureDefinition/[namespace]-[ElementName]. If we always use the same fhirURL in every config file, e.g.,  http://hl7.org/fhir/us/shr, then the FQN should be stable. The downside is that the namespace is packed into the element name (such as shr-entity-Patient), not earlier in the URL. Is that a workaround?  Regardless the documentation on the profile page says "Reference(oncocore Patient Profile)" when it should say Reference(shr-entity-Patient).

**Comment by markkramerus** [comment]
However, value sets march to a different drum. For example:

Name: oncocore PresentAbsentVS ValueSet
Defining URL: [**projectURL**]/shr/base/vs/PresentAbsentVS

To be consistent with above, this would be [fhirURL]/vs/shr-base-PresentAbsentVS, e.g., http://hl7.org/fhir/us/shr/vs/shr-base-PresentAbsentVS.

**Comment by markkramerus** [comment]
BTW, if /shr is part of the FQN, there's no reason to have the shr in the namespaces.

**Comment by cmoesel** [comment]
You got the basic algorithm right.  If I recall, the VS URLs are different because we wanted them to be independent of FHIR (e.g., a value set definition is applicable across many representations whereas a FHIR profile is by-definition FHIR only).  I'm not sure that distinction really holds up, but I think that's the deal.  If I recall though, when the `projectURL == fhirURL`, some additional magic happens and the algorithm for the VS URL changes to match the FHIR scheme.  I think.

As for the redundancy w/ `shr` in the url prefix and in the namespace, that redundancy is created because `shr` exists in the URL _and_ in the namespace.  In other words, if that redundancy should be removed, I think it's up to the author to either modify the namespace or modify the url.  That said, I supposed we could create some other convention that allows for "default" namespaces (or "default" namespace roots) that get suppressed.

That said, if we fix this so URLs for things like `shr-entity-Patient` don't change, then we have a different problem: multiple IGs all publishing the _same_ profiles (but potentially with differences in content).  I think the real solution will have to be a more modular approach such that when you use `shr-entity-Patient`, you're clearly importing it from another package/IG (along with its original URL) and _not_ re-publishing it in your own IG.  We need to get there.

**Comment by cmoesel** [comment]
> Regardless the documentation on the profile page says "Reference(oncocore Patient Profile)" when it should say Reference(shr-entity-Patient).

As for this, the FHIR IG Publisher creates the text of the reference using the name of the profile it references.  We currently export the name as `${config.projectShortName} ${element.name} Profile`.  That can be changed.

**Comment by markkramerus** [comment]
I noticed the version value on the profile is the version of the IG (see code snippet). This is not correct since the profile version and IG versions are independent of each other. You should be able to rev the IG without revising the profiles.

`  <identifier>
    <system value="http://hl7.org/fhir/us/projectURL"/>
    <value value="shr.encounter.Encounter"/>
  </identifier>
  **<version value="0.6.0"/>**  // this is the IG version
  <name value="Encounter"/>
  <display value="shr-encounter-Encounter"/>
  <status value="draft"/>`

**Comment by markkramerus** [comment]
Closed and moved this discussion to https://github.com/standardhealth/shr_spec/wiki/Packaging-Requirements
