### ISSUE TITLE
The History Link is broken on the generated IG.

### ISSUE THREAD

**Issue by mlterryMitre** [standardhealth/shr-cli#138]
Tested with shr-cli-5.13.0-beta.1: In the generated FHIR IG, the "History" link in the top tab shows a link to hl7.org/fhir/us/oncocore (or whatever primary namespace name we generate/history.html.  This generates an HTML 404 "File Not Found" message when clicked.
Suggestion is to place a stub page in its place if there is no config file option to remove the link.

**Comment by cmoesel** [comment]
Hi @mlterryMitre.  The history link is actually specified in the config file.  You're seeing a history link (and that specific history link) because that's how it's configured in the oncocore spec.

I actually submitted a pull request to the spec last night to address this issue (and the empty logical models).  See: https://github.com/standardhealth/shr_spec/pull/204

**Comment by markkramerus** [comment]
The package file with history is now required, but we've also learned that the history is 404 until the package is deployed to the HL7 build server. Closing.
