### ISSUE TITLE
Message for Error Code 12007

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#45]
Please add the EntryElement name (ProviderOrganization in the example) to error message 12007.

[17:04:33.645Z] ERROR shr: Cannot override RefValue<shr.base.Object> with RefValue<shr.actor.Organization>. ERROR_CODE:12007 (module=shr-expand, shrId=shr.base.Party)

meant I had to change:

EntryElement:	ProviderOrganization
Based on:	Party
Value:		ref(Organization)
1..1    		NationalProviderIdentifier

to:

EntryElement:	ProviderOrganization
Based on:	Party
			Value is type ref(Organization)
1..1    		NationalProviderIdentifier

It would have been 100% easier if the message had a hook to ProviderOrganization

**Comment by cmoesel** [comment]
This actually raises a different issue, in that I didn't think there was a meaningful difference between the two entries above.  It seems to me they are both attempting to do the same thing -- so I don't know why one works and not the other.

We are generally including the entry element in the log, and in this case, it says the issue is in "Party" -- so again, the fact that the fix was in ProviderOrganization is surprising.

**Comment by markkramerus** [comment]
Moved to Jira Issue Tracker, https://standardhealthrecord.atlassian.net/browse/CIMPL-43
