### ISSUE TITLE
Don't know how to constrain Frequency

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#58]
The intent is to derive Frequency (number/time) from Ratio by constraining the numerator to be a count and denominator to be a quantity with time units.  I can't seem to find the right grammar, though. Please advise.

Element:		Frequency   // TODO: should be a ratio, but the problem is that ratio uses Quantity in numerator and denominator
Based on:		Ratio
Concept:		MTH#C0376249
Description:	"How many occurrences of an event per unit of time."
//1..1			Numerator.Quantity.Units is UCUM#1
//1..1			Denominator.Quantity.Units from http://hl7.org/fhir/ValueSet/units-of-time

**Comment by cmoesel** [comment]
In the `flux_a` branch, I had changed this to:
```
Numerator.Quantity with units UCUM#1
Denominator.Quantity.Units with Coding from http://hl7.org/fhir/ValueSet/units-of-time
```

That said, looking further at the shr_spec, I think it could also be represented like this:
```
Numerator value is type Qount
Denominator value is type Duration
```

One thing I've noticed is that mapping a `Quantity` field into FHIR is a bit tricky because we make `Units` a standalone type, whereas FHIR has the `unit/code` and `system` flattened into the `Quantity` type.  So if we put a constraint on the `Quantity.Units` field (like `1..1`), it's hard to know how to materialize that into FHIR since there is no direct correlation from `Quantity.Units` to a single FHIR field.

We could also consider aligning more closely to FHIR's [`Timing`](http://build.fhir.org/datatypes.html#Timing) type, which looks nothing like our current `Frequency` class, but is notable more complex.

What are the concerns/issues you're running into?

**Comment by gregquinn2001** [comment]
We aren't using numerator or denominator right now so feel free to change them in the flux branch.

**Comment by markkramerus** [comment]
Fixed a while back. Here's the definition of Frequency:
`Group:             Frequency
Parent:            Ratio
Description:       "How many occurrences of an event per unit of time."
                   Numerator[Quantity].Units = UCUM#1
                   Denominator[Quantity].Units from http://hl7.org/fhir/ValueSet/units-of-time (required)`
