### ISSUE TITLE
Namespaces garbled or missing

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#71]
I removed shr. prefix from namespaces for the ballot (may-2018-ballot branch). For example, I changed shr.finding to finding. The FHIR IG profile summary page is missing the namespaces.

**Comment by markkramerus** [comment]
Another thing. A dash seems to "create" a namespace out of whatever precedes the dash:

namespace|name|based on|definition
**Ki** | Ki-67LabelingIndex | Observation | Ki-67 is a protein phosphatase...

**Comment by cmoesel** [comment]
I think there may be some assumptions in the IG generators (our code, not FHIR's) about the `shr` prefix.  We trim the SHR namespace prefix in the table so it would be more concise and readable -- but obviously we made it a bit too rigid.  This fix shouldn't be too difficult.  In the worst case, we just remove the trimming and deal with the longer SHR namespaces.

As for the `-` (dash) issue:  In SHR, we use `.` (dot) to separate namespaces, but in FHIR, `.` (dot) is only used for traversing paths.  For this reason, we have to convert a namespace like `my.special.namespace` to something that is FHIR friendly, and we chose to replace `.` (dot) with `-` (dash) for this purpose (e.g., `my-special-namespace`).  It appears that somewhere, however, we're trying to reverse the process and mistakenly splitting on a dash in the _name_.  I think we can just be more smart about the split though, because namespace parts always start with a lowercase letter (`a-z`) and element names always start with an uppercase letter (`A-Z`) -- so we still should be able to determine where the namespace really ends.

**Comment by cmoesel** [comment]
Fixed in the following `shr-fhir-export` commit (currently on `logical_models` branch):
https://github.com/standardhealth/shr-fhir-export/commit/62495f7c5c1c71faac914c17014208a569b1c359

A more recent commit, however, renders this moot, as it no longer displays the namespaces on the summary pages.
