### ISSUE TITLE
Profile extensions are missing

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-cli#84]
I'm not seeing all the extensions that should be present in profiles. For example, in BreastCancerPresenceStatementProfile there should be extensions for BodySite (type BreastBodySite), TopicCode, and ContextCode (and maybe others).  
Not sure at what point they "went missing"....

**Comment by cmoesel** [comment]
This is another thing where I think CIMI is causing trouble.  We generate extensions for _top-level_ unmapped fields.  You are mapping some parts of `ConditionTopic`, so `ConditionTopic` doesn't become an extension, nor do subfields of `ConditionTopic`.  For one, it would be unclear where those sub-fields should actually go (is it appropriate to map a _nested_ SHR field to a top-level extension in a FHIR profile?  Not always!

(More to come later -- have to go to meeting).

**Comment by markkramerus** [comment]
As we discussed, this is a deeper issue, and it will take some thought. I would actually like to be able to build a class with the topic and context both appearing as "based on" classes, which would partly address this issue by making the attributes of ConditionTopic and ConditionPresenceContext appear at the top level. But this is only a partial solution since we are always going to run into nested unmapped attributes. So we really do have to solve this issue.

**Comment by notpace** [comment]
Has there been any further discussion on this issue?  I'm working on a set of profiles to model medication formularies and would like for the shr-cli tool to create extensions from unmapped fields on both on the _top-level_ element _and_ one of its children.

**Comment by cmoesel** [comment]
Hi Pace.  We started this work, but some of it was OBE, due to HL7 ballots, urgent need for DSTU2 support, and a push toward CIMPL v6. Realistically, we likely won't see it until CIMPL 6.x.  It's something I've thought about in my initial proposed design for the CIMPL v6.x FHIR mapping language.  That's still in the early stages, and I don't think is documented on GitHub yet, but I'll try to get it to you.  What is your timeline for needing this?

**Comment by markkramerus** [comment]
Pace brought this issue up again (thank you for pushing, Pace).  I think the FHIR profile should follow the structure of the CIMPL object, unless otherwise specified. 

For example, if CIMPL says this:

`EntryElement:  Foo
0..1   Goo
Element: Goo
0..1    Hoo
0..1    Koo`

and 
`Foo maps to FhirFoo:
    Goo maps to fhirGoo
    Hoo maps to fhirHoo`

where 

`Resource 
FhirFoo
0..1  fhirGoo  // backbone element
|---  0..1 fhirHoo
`

Since Koo is an element of Goo, and Goo maps to FhirGoo, and Koo is not mapped, then by default Koo should extend FhirGoo. No additional grammar necessary.

**Comment by cmoesel** [comment]
I may be wrong, but when I spoke with @notpace, it sounded like he wanted to map a _top-level_ field to a nested extension.  In other words (using your example) -- I think his use case is more like this:

```
EntryElement:  Foo
0..*   Goo
0..1   Hoo
0..1   Koo
```

and he wants to map Hoo and Koo as extensions of FHIRFoo's fhirLoo attribute.

```
Foo maps to FhirFoo:
    Goo maps to fhirGoo
    Hoo maps to fhirLoo.extension
    Koo maps to fhirLoo.extension
```

Since Hoo and Koo are top-level, but the target destination is nested, I don't think there is any way to imply the correct mapping.

**Comment by notpace** [comment]
@cmoesel that was my use case for the formulary IG, but I've been working on something that is more similar to the example that @markkramerus laid out - the fields are included in the CIMPL mapping as child elements but are not being created as extensions on the corresponding FHIR elements.

**Comment by cmoesel** [comment]
OK.  So ideally you need both!  Got it.

**Comment by markkramerus** [comment]
Fixed in 5.x some time ago. The grammar of Foo maps to bar.extension is supported.
